### ISSUE TITLE
Not blocking at all

### ISSUE THREAD

**Issue by m0Chandras** [stu-blair/game-of-spoils#11]
Doesn't seem to be working at all on my side. Even went ingognito with all extensions off except for GoS and it doesn't even block results from a simple google search

**Comment by stu-blair** [comment]
Hi @muhammedchand , what sites are you seeing that it doesn't work? Please note that it isn't supposed to block results from a google search. For Google, it is only supposed to block things when you are browsing through Google News.

**Comment by stu-blair** [comment]
Closing due to no response
