### ISSUE TITLE
FR: Please add a mode that just removes content, black outs are more annoying than what it's blocking

### ISSUE THREAD

**Issue by ThoughtPhotography** [stu-blair/game-of-spoils#6]
There's a lot of people that aren't worried about spoilers, but just don't GaF about Game of Thrones period.

Can you please add an option to just remove content and not replace it with anything? Seeing giant blackouts and stupid GoT phrases in the newsfeed is actually more annoying than the content it's blocking...

Thanks!

**Comment by stu-blair** [comment]
Added this feature in b2988ed97723e4c1997 ! Let me know if this fulfills your desires. I agree 'hiding' is a lot nicer than 'blocking' most of the time.
